### ISSUE TITLE
I have Pcap file mode in my tool WIre

### ISSUE THREAD

**Issue by puppetpies** [maiha/pcap.cr#4]
Its a pretty simple change it you would like to include it in your sniffer.

https://github.com/puppetpies/WIre/commit/d04637fb4598a487bfb63cf3f25e10ff3b3cf2b4

Regards,

Brian

**Comment by maiha** [comment]
Nice work!
I'll merge it in this weekends.
Thanks!

**Comment by maiha** [comment]
Merged into `tcpsniffer` with tiny change about option name! And released v0.2.4!
Thanks again :tada:

**Comment by puppetpies** [comment]
I've merged the option name over here as well.
