### ISSUE TITLE
UDP Packet support

### ISSUE THREAD

**Issue by puppetpies** [maiha/pcap.cr#6]
UDP Packet support doesn't seem to exist at the moment in your pcap.cr are you planning to build this.

If its not on your roadmap for now i can take a look.

Brian,

**Comment by maiha** [comment]
No plans yet.

> If its not on your roadmap for now i can take a look.

Nice! Please try it!
I could help you when you will face some weird codes and behaviors.

regards

**Comment by puppetpies** [comment]
Yeah UDP support is something i would like in my project  and will be doing a lot of code next week so i will just a create a branch a work locally till things start to work !
